### ISSUE TITLE
Can't create and update the e2e tests vcs project without rebooting the node

### ISSUE THREAD

**Issue by zadigus** [shopozor/backend#51]
Ticket [##14487##] opened on our Jelastic provider. It seems like it is not possible anymore to do (cf. [e2e manifest](https://github.com/shopozor/backend/blob/dev/e2e/manifest.jps))

```yml
deployRepo:
      api:
        - method: environment.vcs.CreateProject
          params:
            type: git
            context: ${globals.CONTEXT}
            url: https://github.com/softozor/shopozor-backend
            branch: GIT_BRANCH
            login: GIT_USER
            password: GIT_PASSWORD
        - method: environment.vcs.Update
          params:
            context: ${globals.CONTEXT}
      nodeGroup: cp
```
The work-around is currently this:
```yml
deployRepo:
      - api [cp]:
        - method: environment.vcs.CreateProject
          params:
            type: git
            context: ${globals.CONTEXT}
            url: https://github.com/softozor/shopozor-backend
            branch: GIT_BRANCH
            login: GIT_USER
            password: GIT_PASSWORD
      - restartNodes:
        - nodeGroup: cp
      - api[cp]:
        - method: environment.vcs.Update
          params:
            context: ${globals.CONTEXT}
```
It is not a big deal but slows down the deployment. With the previous Jelastic versions, it was working without the above work-around.
